---

version: "3"
services:
  pe_reports-rabbitmq:
    command:
      - rabbitmq-server
    container_name: pe_reports-rabbitmq
    entrypoint:
      - docker-entrypoint.sh
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - PATH=/opt/rabbitmq/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - RABBITMQ_DATA_DIR=/var/lib/rabbitmq
      - RABBITMQ_VERSION=3.8.14
      - RABBITMQ_HOME=/opt/rabbitmq
      - RABBITMQ_LOGS=-
      - HOME=/var/lib/rabbitmq
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    hostname: 7ccb5fe7f56c
    image: rabbitmq:3.8.14-management
    ipc: private
    labels:

      com.docker.compose.container-number: 1
      com.docker.compose.oneoff: False
      com.docker.compose.project: pe_reports
      com.docker.compose.project.config_files: docker-compose.yaml

      com.docker.compose.service: rabbitmq
      com.docker.compose.version: 1.29.2
    logging:
      driver: json-file
      options: {}
    networks:
      - pe_reports_pe-reports-rabbitmq-network
    ports:
      - 15672:15672/tcp
      - 5672:5672/tcp
    restart: always
    volumes:
      # If on a local
      # - /Users/${USER}/Desktop/allInfo/pe-reports-UIupgrade/
      # src/pe_reports/data/rabbitmq/data:/var/lib/rabbitmq/mnesia:rw
      - /home/ubuntu/pe-reports/src/pe_reports/data/rabbitmq/data:/var/lib/rabbitmq/mnesia:rw
networks:
  pe_reports_pe-reports-rabbitmq-network:
    external: true
    name: pe_reports_pe-reports-rabbitmq-network
